### ISSUE TITLE
qBittorrent/4.1.9.1 - Plugin iptorrents is not supported.

### ISSUE THREAD

**Issue by tsposato** [txtsd/qB-IPT#4]
Hi,

I'm trying to use your plugin in freenas qbittorrent plugin and I get the following error in the logfile:

(I) 2020-01-31T21:39:42 - Plugin iptorrents is not supported.

Other plugins seems to load fine.
Version: qBittorrent v4.1.9.1
O/S: FreeBSD

Is there anything I can try to fix this?

**Comment by txtsd** [comment]
According to https://github.com/qbittorrent/search-plugins/issues/121, plugin support is going to be dropped in favor of better Jackett integration.

**Comment by element4l** [comment]
@txtsd do you know when better jackett support is coming? The current functionality is ok but I would like to be able to sort by tracker instead of having everything under a single source, you know what I mean?

**Comment by txtsd** [comment]
Sorry, I have no idea. You should ask on the linked repo instead.
I just use jackett in my browser.
